development:
  address:              localhost
  port:                 1025

test:

production:
  address:              "smtp.gmail.com",
  port:                 25,
  domain:               "fancy_gifts_shop.net",
  authentication:       "plain",
  user_name:            "truly.pully",
  password:             "secret",
  enable_starttls_auto: true